# Site settings
# title: "A  real tragic story <br> (′○` ))"
title: "  ❤ 陈一 ❦"
author: "ChenJ"
description: "A random blog"
keywords: " Mathematics, Philosophy, Scala, Epistemology, Existentialism,  Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"

biography: "开开心心过好每一天　多读书　<a href='http://music.163.com/'>多听歌</a>"

colophon: "Created with <a href='http://jekyllrb.com/'>Jekyll</a>."
baseurl: ""
url: "http://aaying.xyz/"
city: 温州/宁波

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /:year:month:day/
